comum/urls.py
from django.urls import path, include
from .views import home
from store import urls as store_urls

urlpatterns = [
    path('', home, name='normal_home'),
    # path('login/', login, name='login'),
    # path('new_user/', register, name='register'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from comum import urls as comum_urls
from client import urls as client_urls
from store import urls as store_urls
from frontend import urls as frontend_urls
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    # path('', include('registration.backends.default.urls')),
    path('', include(comum_urls)),
    # path('', include(client_urls  )),
    # path('', include(store_urls)),
    # path('', include(frontend_urls)),
    # path('', include('django.contrib.auth.urls')),
    # path('api-auth/', include('rest_framework.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path, include
from .views import store, new_product, products, dashboard, product, delete_product, orders, order, finish_order, edit_order, settings, edit_store_profile, add_category, login, register, edit_intermediate, load_options
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings as set

# The first <int:id> must be the store id
urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),

    path('', store, name='store'),
    path('dashboard/', dashboard, name='dashboard'),
    path('orders/', orders, name='orders'),
    path('order/<int:order_id>', order, name='order'),
    path('edit_order/<int:order_id>', edit_order, name='edit_order'),
    path('edit_intermediate/<int:intermediate_id>', edit_intermediate, name='edit_intermediate'),
    path('finish_order/<int:order_id>', finish_order, name='finish_order'),
    path('add_product/', new_product, name='new_product'),
    path('products/', products, name='products'),
    path('delete_product/<int:product_id>/', delete_product, name='delete_product'),
    path('product/<int:product_id>/', product, name='product'),
    path('settings/', settings, name='settings'),
    path('settings/edit_store_profile', edit_store_profile, name='edit_store_profile'),
    path('add_category/<int:store_id>/', add_category, name='add_category'),

    path('load_options/', load_options, name='load_options'),

    # path('accounts/',admin.site.urls),
] + static(set.MEDIA_URL, document_root=set.MEDIA_ROOT)

store/models.py
from django.db import models
from client.models import User
from django.contrib.postgres.fields import JSONField, ArrayField

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'store/{}'.format(filename)

class Store(models.Model):
    owner = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.FileField(upload_to=user_directory_path, default='default.jpg')
    name = models.CharField(max_length=254, default='', unique=True)
    description = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE, default=None, blank=True, null=True)
    category = models.CharField(max_length=256)

    def __str__(self):
        return self.category

class Products(models.Model):
    PRODUCT_STATUS = (
        ('ATIVO', 'Ativo'),
        ('INVISIVEL', 'Invisível'),
        ('SEM_ESTOQUE', 'Sem Estoque'),
        ('EM_BREVE', 'Em Breve'),
    )

    store_owner = models.ForeignKey(Store, on_delete=models.CASCADE)
    avatar = models.FileField(upload_to=user_directory_path, default='default.jpg')
    name = models.CharField(max_length=254)
    description = models.CharField(max_length=254, blank=True, null=True)
    status = models.CharField(max_length=254, choices=PRODUCT_STATUS, default='ATIVO')
    price = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    featured = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=None, null=True, blank=True)
    has_option = models.BooleanField(default=False)
    options = JSONField(blank=True, null=True)

    def __str__(self):
        return self.name

class Product_Option(models.Model):
    product_owner = models.ForeignKey(Products, on_delete=models.CASCADE, null=True, blank=True)
    type = models.CharField(max_length=256, null=True, blank=True)
    value = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.type

class Order(models.Model):
    # Order Info
    active = models.BooleanField(default=False)
    store_owner = models.ForeignKey(Store, on_delete=models.CASCADE)
    order_number = models.CharField(max_length=256)
    product_info = models.ManyToManyField(Products, through='Intermediate_Order_Product')
    order_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    delivered = models.BooleanField(default=False)
    full_price = models.IntegerField(default=0)


    def __str__(self):
        return self.order_number


    def generate_order_number(self):
        first_string = self.store_owner.name.upper()
        first_string = first_string.replace(' ', '')
        second_string = self.id
        return '#{}-{:06d}'.format(first_string, second_string)

    def refresh_full_price(self):
        intermediate = Intermediate_Order_Product.objects.filter(order=self)
        new_full_price = 0
        for intermediate_info in intermediate:
            new_full_price += intermediate_info.product.price * intermediate_info.product_quantity
        self.full_price = new_full_price
        self.save()


    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.order_number = self.generate_order_number()
        super().save(*args, **kwargs)

class Intermediate_Order_Product(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    product_option = models.ForeignKey(Product_Option, on_delete=models.CASCADE, null=True, blank=True)
    product_quantity = models.IntegerField(default=1)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.order.refresh_full_price()
    

class Order_Info(models.Model):
    # Customer Info
    order_owner = models.ForeignKey(Order, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=256, default=None)
    last_name= models.CharField(max_length=256, default=None)
    email = models.EmailField(max_length=256, default=None)
    address = models.CharField(max_length=256, default=None)
    observation_note = models.CharField(max_length=300, null=True, blank=True)

    def __str__(self):
        return self.order_owner.order_number

    def get_full_name(self):
        return ('{} {}'.format(self.first_name, self.last_name))

class Cart(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    product_option = models.ForeignKey(Product_Option, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.product

store/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, get_object_or_404
from .models import Store, Products, Order, Category, Product_Option, Order_Info, Intermediate_Order_Product
from client.models import User
from .forms import NewStoreForm, Product, EditStoreProfileForm, AddCategory, LoginForm, UserCreationForm, Product_Option_FormSet, EditIntermediateForm
from django.conf import settings as project_settings
from django.http import HttpResponse
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout, authenticate
import json
from collections import OrderedDict
import logging

logging.basicConfig(level= logging.DEBUG, format="[%(levelname)s %(filename)s %(lineno)d] %(message)s")

logger = logging.getLogger()

def login(request):
    form = LoginForm(request.POST)
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        try:
            user = User.objects.get(email=username)
        except:
            raise RuntimeError("User doesn't exist on database")

        if user is not None and user.check_password(password):
            user_authenticate = authenticate(username=username, password=password)
            auth_login(request, user_authenticate)
            return redirect('dashboard')
        else:
            print ('Não é pra logar')

    return render(request, 'login.html', {'form': form})

def register(request):
    form = UserCreationForm(request.POST, None)

    if form.is_valid():
        form.save()
        return redirect('login')

    return render(request, 'register.html', {'form': form})


@login_required()
def store(request):
    # logout(request)
    # print ('print: {}'.format(Store.objects.get(name='Hasher').owner))
    # print ('print: {}'.format(request.user))
    return render(request, 'store.html', {'store': store, 'products': products})

@login_required
def new_product(request):
    form = Product(request.POST, request.FILES, None)

    store = Store.objects.get(owner=request.user)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.store_owner = store
        instance.save()
        return redirect('products')

    return render(request, 'new_product.html', {'form': form, 'store': store})

@login_required
def products(request):
    store = Store.objects.get(owner=request.user)
    products = Products.objects.filter(store_owner=store.id)
    # product = Products.objects.get(id=id)
    return render(request, 'products.html', {'store': store, 'products': products})

@login_required
def product(request, product_id):
    product = get_object_or_404(Products, pk=product_id)
    form = Product(request.POST or None, request.FILES or None, instance=product)

    options = Product_Option.objects.filter(product_owner=product)
    l = []
    for option in options:
        l.append(dict(type=option.type, value=option.value))

    formset_data = l
    formset = Product_Option_FormSet(request.POST or None, queryset=options)

    category_form = AddCategory(request.POST or None)

    store = Store.objects.get(owner=request.user)

    print("Tem option?: ", product.has_option)

    if request.method == 'POST':
        if formset.is_valid():
            print('formset valido')
            instance = formset.save(commit=False)
            for option in instance:
                product.has_option = True
                option.product_owner = product
                option.save()
            for obj in formset.deleted_objects:
                obj.delete()

        else:
            print('formset não valido com erro: ', formset.errors)

        if form.is_valid():
            form.save()
            return redirect('products')
        else:
            return redirect('products')

    return render(request, 'product.html', {'store': store, 'product': product, 'form': form, 'category_form': category_form, 'formset': formset})
# return correct json
def json_format(list1, list2):
    final_dict = OrderedDict()
    for item1, item2 in zip(list1, list2):
        print (item1, item2)
        final_dict[item1] = item2
    print (final_dict)
    return final_dict

@login_required
def delete_product(request, product_id):
    product = get_object_or_404(Products, pk=product_id)
    product.delete()
    return redirect('products', id=id)

@login_required
def dashboard(request):
    store = Store.objects.get(owner=request.user)
    return render(request, 'dashboard.html', {'store': store})

@login_required
def orders(request):
    store = Store.objects.first()
    orders = Order.objects.filter(store_owner=store)
    # intermediate_data_objects = [Intermediate_Order_Product.objects.filter(order=order) for order in orders]

    return render(request, 'orders.html', {'orders': orders})

@login_required
def order(request, order_id):
    store = Store.objects.first()
    intermediate_model = Intermediate_Order_Product.objects.filter(order=Order.objects.get(id=order_id))
    order = Order.objects.get(id=order_id)
    order_info = Order_Info.objects.get(order_owner=order)

    return render(request, 'order.html', locals())

@login_required
def edit_order(request, order_id):
    store = Store.objects.get(owner=request.user)
    order = Order.objects.get(id=order_id)
    form = OrderForm(request.POST or None, request.FILES or None, instance=order)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
        return redirect('orders', id=store.id)

    return render(request, 'edit_order.html', {'form': form, 'store': store, 'order': order})

@login_required
def finish_order(request, order_id):

    order = Order.objects.get(id=order_id)
    order.delivered = True
    order.save()

    return redirect('orders')

@login_required
def discount(request):
    store = Store.objects.get(owner=request.user)
    return render(request, 'discount.html', {'store': store})

@login_required
def settings(request):
    store = Store.objects.get(owner=request.user)
    user = User.objects.get(id=store.owner.id)

    return render(request, 'settings.html', {'store': store, 'user': user})

@login_required
def edit_store_profile(request):
    store = Store.objects.get(owner=request.user)
    form = EditStoreProfileForm(request.POST or None, request.FILES or None, instance=store)

    if form.is_valid():
        form.save()
        return redirect('settings')

    return render(request, 'edit_store_profile.html', {'store': store, 'form': form})

@login_required
def add_category(request, store_id):
    store = Store.objects.get(owner=request.user)
    if request.method == 'POST':
        form = AddCategory(request.POST or None)
        temp_form = form.save(commit=False)
        temp_form.store = store
        if form.is_valid():
            # form.save()
            print ("form: {}".format(temp_form.store))
            temp_form.save()
            print ("Deu certo!")
        else:
            print (form.errors)
            print ('Deu ruim')

    return HttpResponse('')

    
@login_required
def edit_intermediate(request, intermediate_id):
    intermediate = get_object_or_404(Intermediate_Order_Product, id=intermediate_id)
    form = EditIntermediateForm(intermediate.product, request.POST or None, instance=intermediate)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('order', order_id=intermediate.order.id)
    # TODO Salvar dados editados
    return render(request, 'edit_intermediate.html', locals())

def load_options(request):
    product_id = request.GET.get('product')
    products_option_qs = Product_Option.objects.filter(product_owner=Products.objects.get(id=product_id))
    print('Got this -> ', products_option_qs)
    return render(request, 'option_dropdown_list_options.html', {'products_option': products_option_qs})

store/templates/dashboard.html
{% extends 'base.html' %}

{% block title %}
    Dashboard
{% endblock %}

{% block content %}
    <div style="display: flex; justify-content: center; height: 100%;">
        Not Implemented
    </div>
{% endblock %}

store/templates/edit_intermediate.html
{% extends 'base.html' %}

{% block title %}
    Editar
{% endblock %}

{% block content %}
<form method="POST" action="{% url 'edit_intermediate' intermediate_id=intermediate.id %}">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-primary">Salvar</button>
</form>
<script>
    $( document ).ready(function() {
        $('#id_product').change(() => {
            $.ajax({
                url: '/load_options',
                data: {
                    'product': $('#id_product').val()
                },
                success: function (data) {
                    $("#id_product_option").html(data);
                }
            });
        });
    });

</script>
{% endblock %}

store/templates/edit_order.html
{% extends 'base.html' %}

{% block title %}
    Editar Pedido
{% endblock %}

{% block content %}
    <form method="post" action="{% url 'edit_order' id=store.id order_id=order.id %}">
        {% csrf_token %}
        {{ form }}
    <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
{% endblock %}

store/templates/edit_store_profile.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    Editar Perfil
{% endblock %}

{% block content %}
    <form method="post" action="{% url 'edit_store_profile' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {% render_field form.avatar.label_tag %}
            {% render_field form.avatar class+="form-control" %}
        </div>
        {% csrf_token %}
        <div class="form-group">
            {% render_field form.name.label_tag %}
            {% render_field form.name class+="form-control" %}
        </div>
        <div class="form-group">
            {% render_field form.description.label_tag %}
            {% render_field form.description class+="form-control" %}
        </div>
    <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
{% endblock %}

store/templates/login.html
{% load static %}
{% load widget_tweaks %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {#  Bootstrap  #}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

    <title>Login</title>
</head>
<body>

    <div class="wrapper">
        <div class="mid-container">
            <h3 class="login-header">Login</h3>
            <div class="login-form">
                <form method="post" action="{% url 'login' %}">
                    {% csrf_token %}
                  <div class="form-group">
                      {% render_field form.username class+='form-control' type='email' name='username' id='username' placeholder='Email' %}
                  </div>
                  <div class="form-group">
                      {% render_field form.password class+='form-control' type='password' name='password' id='password' placeholder='Senha'%}
                  </div>
                  <button type="submit" class="btn btn-primary">Entrar</button>
                    <div class="login-doubt">
                        <a href="{% url 'register' %}">Sem cadastro?</a>
                        <a href="#">Esqueceu sua senha?</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

</body>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
</html>

store/templates/new_product.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    Adicionar Produto
{% endblock %}

{% block content %}
    <form method="post" action="{% url 'new_product' %}" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="form-group">
            {% render_field form.avatar.label_tag %}
            {% render_field form.avatar class+="form-control" %}
        </div>
        <div class="form-group">
            {% render_field form.name.label_tag %}
            {% render_field form.name class+="form-control" %}
        </div>
         <div class="form-group">
             {% render_field form.description.label_tag %}
            {% render_field form.description class+="form-control" %}
        </div>
         <div class="form-group">
             {% render_field form.status.label_tag %}
            {% render_field form.status class+="form-control" %}
        </div>
         <div class="form-group">
             {% render_field form.price.label_tag %}
            {% render_field form.price class+="form-control" %}
        </div>
        <button type="submit" class="btn btn-primary">Criar</button>
    </form>
{% endblock %}

store/templates/new_store.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}New Store{% endblock %}

{% block content %}
    <form method="post" action="{% url 'new_store' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {% render_field form.avatar class+="form-control" %}
        </div>
        <div class="form-group">
            {% render_field form.name class+="form-control" %}
        </div>
        <div class="form-group">
            {% render_field form.description class+="form-control" %}
        </div>
        <button type="submit" class="btn btn-primary">Criar loja</button>
    </form>
{% endblock %}

store/templates/option_dropdown_list_options.html
<option value="">---------</option>
{% for product_option in products_option %}
    <option value="{{ product_option.pk }}">{{ product_option.type }}</option>
{% endfor %}

store/templates/order.html
{% extends 'base.html' %}

{% block title %}
    Pedido
{% endblock %}

{% block content %}
        <div class="order-product-data">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <div class="base-background-card">
                            {{ order.order_number }}
                            <br>
                            {{ order_info.owner.get_full_name }}
                            <br>
                            {{ order_info.email }}
                            <br>
                            Total: {{ order.full_price }}
                            {% comment %} <a class="btn btn-success" href="{% url 'edit_order' id=store.id order_id=order.id %}">Editar informações</a> {% endcomment %}
                        </div>
                    </div>
                    <div class="col-md-9">
                        {% for order_data in intermediate_model %}
                            <div class="base-background-card">
                                <h3>{{ order_data.product.name }}</h3>
                                <a href="{% url 'edit_intermediate' intermediate_id=order_data.id %}"><i class="far fa-edit"></i></a>
                                {% if order_data.product.descrition %}
                                    <p>{{ order_data.product.description }}</p>
                                {% endif %}
                                <p>Quantidade: {{ order_data.product_quantity }}</p>
                                {% if order_data.product.has_option %}
                                    <p>Opção: {{ order_data.product_option }}</p>
                                {% endif %}
                                <img style="width: 30%;" src="{{ order_data.product.avatar.url }}">
                                <p>R$ {{ order_data.product.price }}</p>
                            </div>
                        {% endfor %}
                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModal">
                          Finalizar Pedido
                        </button>
                    </div>
              </div>
            </div>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Finalizar Pedido</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                Deseja confirmar envio de pedido?
              </div>
              <div class="modal-footer">
                    <a class="btn btn-success" href="{% url 'finish_order' order_id=order.id %}">Finalizar Pedido</a>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

store/templates/orders.html
{% extends 'base.html' %}

{% block title %}
    Produtos
{% endblock %}

{% block content %}
    <div class="products-header">
        <h3>Orders</h3>
    </div>
    <div class="container">
          <div class="row">
              
              {% for order in orders %}
                  {% if order.active and not order.delivered %}
                    <div class="col-md-3 my-5">
                        <div class="card" style="width: 18rem;">
                        <a href="{% url 'order' order_id=order.id %}">
                            {% with order.product_info.all|first as first_product %}
                                <img class="card-img-top" src="{{ first_product.avatar.url }}" alt="Card image cap">
                            {% endwith %}
                            <div class="card-body">
                                {% for order_info in order.order_info_set.all %}
                                 <h5 class="card-title">{{ order_info.get_full_name }}</h5>
                                {% endfor %}
                                <p class="card-text">R$ {{ order.full_price }}</p>
                                <p class="card-text">{{ order.order_date|date:"d b Y" }}</p>
                            </div>
                        </a>
                        </div>
                    </div>
                  {% endif %}
              {% endfor %}
                  
              <!-- {% for item in data %}
                {% for intermediate in item %}
                    <div class="col-md-3 my-5">
                        <div class="card" style="width: 18rem;">
                        <a href="{% url 'order' order_id=intermediate.order.id %}">
                            <img class="card-img-top" src="{{ intermediate.product.avatar.url }}" alt="Card image cap">
                            <div class="card-body">
                                {% for order_info in intermediate.order.order_info_set.all %}
                                 <h5 class="card-title">{{ order_info.get_full_name }}</h5>
                                {% endfor %}
                                <p class="card-text">R$ {{ intermediate.order.full_price }}</p>
                                <p class="card-text">{{ intermediate.order.order_date|date:"d b Y" }}</p>
                            </div>
                        </a>
                        </div>
                    </div>
                {% endfor %}
              {% endfor %} -->
          </div>
    </div>
{% endblock %}

store/templates/register.html
{% load static %}
{% load widget_tweaks %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {#  Bootstrap  #}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

    <title>Register</title>
</head>
<body>

    <div class="wrapper">
        <div class="mid-container">
            <h3 class="login-header">Novo Usuário</h3>
            <div class="login-form">
                <form action="{% url 'register' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        {% render_field form.email.label %}
                        {% render_field form.email class+="form-control" placeholder="Email" %}
{#                        {{ form.email.errors }}#}
                    </div>
                    <div class="form-group">
                        {% render_field form.store_name.label_tag %}
                        {% render_field form.store_name class+="form-control" placeholder="Loja" %}
{#                        {{ form.last_name.errors }}#}
                    </div>
                    <div class="form-group">
                        {% render_field form.password1.label_tag %}
                        {% render_field form.password1 class+="form-control" placeholder="Senha" type="password" %}
{#                        {{ form.password1.errors }}#}
                    </div>
                    <div class="form-group">
                        {% render_field form.password2.label_tag %}
                        {% render_field form.password2 class+="form-control" placeholder="Confirmar Senha" type="password" %}
{#                        {{ form.password2.errors }}#}
                    </div>
                  <button type="submit" class="btn btn-primary">Entrar</button>
                </form>
            </div>
        </div>
    </div>

</body>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
</html>

store/templates/settings.html
]{% extends 'base.html' %}

{% block title %}
    Settings
{% endblock %}

{% block content %}
    <div class="wrapper">
        <div class="container text-center">
          <div class="row">
            <div class="col-md-12">
                <div class="settings-header mx-auto">
                    <div class="container">
                      <div class="row">
                        <div class="col-md-3">
                          <img class="img-fluid rounded-circle" src="{{ store.avatar.url }}">
                        </div>
                          <div class="col-md-8">
                            <h3>{{ store.name }}</h3>
                              {% if store.description is not None %}
                                <p>{{ store.description }}</p>
                              {% endif %}
                              <p>{{ user.email }}</p>
                              <a class="btn btn-primary" href="{% url 'edit_store_profile' %}">Editar Perfil</a>
                        </div>
                      </div>
                    </div>
                </div>
            </div>
          </div>
        </div>
    </div>
{% endblock %}

store/templates/store.html
{% extends 'base.html' %}

{% block title %}
    Store
{% endblock %}


{% block content %}
    {% comment %}<div class="text-center">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
            Adicionar Produto
        </button>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Adicionar Produto</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>{% endcomment %}
{% endblock %}